[package]
name = "ai-pdf-filler"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.4.1"
chatgpt_rs = "1.2.3"
derive-error = "0.0.5"
lopdf = "0.31.0"
tokio = { version = "1.34.0", features = ["full"] }
